/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customers;

import Forms.EntityForms.*;
import Entity.Customer;
import Entity.Product;
import company.TheTools;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author framawy
 */
public class CustomersStore extends javax.swing.JFrame {

    /**
     * Creates new form DepartmentForm
     */
    public CustomersStore() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMyButton1 = new Controls.JMyButton();
        jMyButton8 = new Controls.JMyButton();
        btnGroub = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcolno = new Controls.JTextBox(15);
        jLabel5 = new javax.swing.JLabel();
        rdoNumber = new javax.swing.JRadioButton();
        rdoName = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbalance = new javax.swing.JTable();
        txtSearch = new Controls.JTextBox(10);
        txtname = new Controls.JTextBox(15);
        jLabel8 = new javax.swing.JLabel();
        rdodate = new javax.swing.JRadioButton();
        bdnback = new javax.swing.JButton();
        bdnall = new javax.swing.JButton();
        bdnclear = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        bdnsearch = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtreceiptno = new Controls.JTextBox(15);
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        txtbalance = new Controls.JTextBox(15);
        txtdate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtpay = new Controls.JTextBox(15);
        txttake = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rdobalance = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        home = new javax.swing.JButton();

        jMyButton1.setText("jMyButton1");

        jMyButton8.setText("jMyButton8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ارصدة حساب العملاء");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("رقم العميل");

        txtcolno.setEditable(false);
        txtcolno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcolno.setForeground(new java.awt.Color(0, 0, 0));
        txtcolno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcolnoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ابحث باستخدام");

        rdoNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoNumber.setForeground(new java.awt.Color(255, 255, 255));
        rdoNumber.setSelected(true);
        rdoNumber.setText("رقم العميل");
        rdoNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNumberActionPerformed(evt);
            }
        });

        rdoName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoName.setForeground(new java.awt.Color(255, 255, 255));
        rdoName.setText("اسم العميل");
        rdoName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNameActionPerformed(evt);
            }
        });

        tblbalance.setAutoCreateRowSorter(true);
        tblbalance.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        tblbalance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "الرقم العميل", "اسم العميل", "التاريخ", "الرصيد"
            }
        ));
        tblbalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbalanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblbalance);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        txtname.setEditable(false);
        txtname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("رقم التحصيل");

        rdodate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdodate.setForeground(new java.awt.Color(255, 255, 255));
        rdodate.setText("التاريخ");
        rdodate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdodateActionPerformed(evt);
            }
        });

        bdnback.setBackground(new java.awt.Color(255, 255, 255));
        bdnback.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnback.setForeground(new java.awt.Color(0, 0, 0));
        bdnback.setText("الرجوع للنافذة السابقة");
        bdnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnbackActionPerformed(evt);
            }
        });

        bdnall.setBackground(new java.awt.Color(204, 204, 0));
        bdnall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdnall.setForeground(new java.awt.Color(0, 0, 0));
        bdnall.setText("اظهار كل الزبائن");
        bdnall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnallActionPerformed(evt);
            }
        });

        bdnclear.setBackground(new java.awt.Color(255, 255, 255));
        bdnclear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnclear.setForeground(new java.awt.Color(0, 0, 0));
        bdnclear.setText("البدء");
        bdnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnclearActionPerformed(evt);
            }
        });

        txtid.setEditable(false);
        txtid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtid.setForeground(new java.awt.Color(0, 0, 0));

        bdnsearch.setBackground(new java.awt.Color(153, 255, 153));
        bdnsearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdnsearch.setForeground(new java.awt.Color(0, 0, 0));
        bdnsearch.setText(" بحث");
        bdnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnsearchActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("اسم الزبون");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("رقم الفاتورة");

        txtreceiptno.setEditable(false);
        txtreceiptno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtreceiptno.setForeground(new java.awt.Color(0, 0, 0));
        txtreceiptno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreceiptnoActionPerformed(evt);
            }
        });

        tbl.setAutoCreateRowSorter(true);
        tbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "رقم العميل", "الاسم", "بضاعة", "دفعة", "رقم الفتورة", "رقم التحصيل", "التاريخ"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl);

        txtbalance.setEditable(false);
        txtbalance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtbalance.setForeground(new java.awt.Color(0, 0, 0));

        txtdate.setEditable(false);
        txtdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtdate.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("دفعة");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("بضاعة");

        txtpay.setEditable(false);
        txtpay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpay.setForeground(new java.awt.Color(0, 0, 0));

        txttake.setEditable(false);
        txttake.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttake.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("الرصيد");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("التاريخ");

        rdobalance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdobalance.setForeground(new java.awt.Color(255, 255, 255));
        rdobalance.setText("الرصيد");
        rdobalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdobalanceActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ارصدة الزبائن");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("كشف حساب العملاء");

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        home.setForeground(new java.awt.Color(0, 0, 0));
        home.setText("المنزل");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bdnsearch)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bdnback)
                                .addGap(18, 18, 18)
                                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(rdodate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdobalance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bdnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bdnall, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtreceiptno)
                                        .addComponent(txtcolno, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtdate)
                                        .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(129, 129, 129)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtid)
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txttake)
                                .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txttake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtreceiptno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcolno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(bdnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(bdnall, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoNumber)
                            .addComponent(rdodate)
                            .addComponent(rdoName)
                            .addComponent(rdobalance))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdnsearch))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bdnback, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      btnGroub.add(rdoNumber);
      btnGroub.add(rdoName);
       btnGroub.add(rdobalance);
        btnGroub.add(rdodate);
     
    //  btnGroub.add(rdomoney);
      btnGroub.add(rdodate);
    //   btnGroub.add(rdodetails);
      cleardata();
      ct.getAllRows(tbl);
      cb.getAllRows(tblbalance);
      txtSearch.setText("0");
    
      tblbalance.getTableHeader().setReorderingAllowed(true);
    }//GEN-LAST:event_formWindowOpened

           Customerstatement ct = new Customerstatement();
     customerbalance cb = new customerbalance();
    private void cleardata(){
        TheTools.clearText(this);
      
      
      
        txtname.requestFocus();
         txtSearch.setText("0"); 
         txtcolno.setText("0");
    }
    
    /*
    private void setValue(){
    ct.setIdcustomer(Integer.parseInt(txtid.getText()));
    ct.setName(txtname.getText());
     // ct.setStorename(txtstorename.getText());
     
       ct.setDate(txtdate.getText()); 
   ct.setBalance(Integer.parseInt(txttotal.getText()));
    
}
    */
    
    private void tblbalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbalanceMouseClicked
        try{
        int row = tblbalance.getSelectedRow();
        
        
        String id =(String) tblbalance.getValueAt(row , 0);
        String name = tblbalance.getValueAt(row, 1).toString();
         
        String date =(String) tblbalance.getValueAt(row , 2);
       String total =(String) tblbalance.getValueAt(row , 3);
        


        txtid.setText(id);
        txtname.setText(name);
        
        //txtstorename.setText(storename); 
        
    
        txtreceiptno.setText("");
        txtcolno.setText("");
        
        
         
          txttake.setText("");
         txtpay.setText("");
        
              txtdate.setText(date);
           txtbalance.setText(total);
        
        
        }
        catch(Exception ex){
            
            TheTools.msgBox(ex.getMessage());
        }
    }//GEN-LAST:event_tblbalanceMouseClicked
 
    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
      
    }//GEN-LAST:event_txtSearchActionPerformed

    private void rdoNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNameActionPerformed

    private void rdoNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNumberActionPerformed

    private void rdodateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdodateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdodateActionPerformed

    private void bdnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnbackActionPerformed
        // TODO add your handling code here:
            this.dispose();
      Customers.CustStart emp = new   Customers.CustStart();
        
       
       emp.setLocationRelativeTo(null);
       emp.setDefaultCloseOperation(2);
      emp.getContentPane().setBackground(new Color(50, 100, 50));
       emp.setVisible(true);
    }//GEN-LAST:event_bdnbackActionPerformed

    private void bdnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnclearActionPerformed
        // TODO add your handling code here:
         cleardata();
        tblbalance.setSelectionMode(0);
        
    }//GEN-LAST:event_bdnclearActionPerformed

    private void bdnallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnallActionPerformed
        // TODO add your handling code here:
         ct.getAllRows(tblbalance);
         cb.getAllRows(tbl);  
    }//GEN-LAST:event_bdnallActionPerformed

    private void txtcolnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcolnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcolnoActionPerformed

    private void bdnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnsearchActionPerformed
        // TODO add your handling code here:
        
        String strSearch = "select * from customerbalance where ";
        if(rdoNumber.isSelected()){
            strSearch += "idcustomer ";
        }
        else if(rdoName.isSelected()){
            strSearch += "name";
        }
        else if(rdobalance.isSelected()){
            strSearch += "balance";
        }
      
       // else if(rdodetails.isSelected()){
      //      strSearch += "storename";
        //}
        else{
            strSearch += "date";
        }
        strSearch += " like '%"+  txtSearch.getText()  +"%'";
        ct.getCustomRows(strSearch, tblbalance);
    }//GEN-LAST:event_bdnsearchActionPerformed

    private void txtreceiptnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreceiptnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreceiptnoActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:

        try{
            int row = tbl.getSelectedRow();

            String id = tbl.getValueAt(row, 0).toString();
            String name =(String) tbl.getValueAt(row, 1);
            String take =(String) tbl.getValueAt(row, 2);

            String pay =(String) tbl.getValueAt(row, 3);
            String receiptno =(String) tbl.getValueAt(row, 4);
            String collectionno =(String) tbl.getValueAt(row, 5);
            String date =(String) tbl.getValueAt(row, 6);
           
               
            txtid.setText(id);
            txtname.setText(name);
          txttake.setText(take);
         txtpay.setText(pay);
         txtreceiptno.setText(receiptno);
           txtcolno.setText(collectionno);
              txtdate.setText(date);
          
        }
        catch(Exception ex){

            TheTools.msgBox(ex.getMessage());
        }
    }//GEN-LAST:event_tblMouseClicked

    private void rdobalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdobalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdobalanceActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Entry en = new Entry();

        en.setLocationRelativeTo(null);
        en.setDefaultCloseOperation(2);
        en.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomersStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomersStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomersStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomersStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomersStore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdnall;
    private javax.swing.JButton bdnback;
    private javax.swing.JButton bdnclear;
    private javax.swing.JButton bdnsearch;
    private javax.swing.ButtonGroup btnGroub;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private Controls.JMyButton jMyButton1;
    private Controls.JMyButton jMyButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdoName;
    private javax.swing.JRadioButton rdoNumber;
    private javax.swing.JRadioButton rdobalance;
    private javax.swing.JRadioButton rdodate;
    private javax.swing.JTable tbl;
    private javax.swing.JTable tblbalance;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JTextField txtcolno;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpay;
    private javax.swing.JTextField txtreceiptno;
    private javax.swing.JTextField txttake;
    // End of variables declaration//GEN-END:variables
}
