/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suppliers;

import Customers.*;
import processForm.*;
import Process.Importclass;
import Process.store;
import company.TheTools;
import java.awt.Color;

/**
 *
 * @author HP
 */
public class Payement extends javax.swing.JFrame {

   
    public Payement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        txtnotes = new Controls.JTextBox(15);
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtid1 = new Controls.JTextBox(15);
        txtaddress = new Controls.JTextBox(15);
        txtname = new Controls.JTextBox(15);
        jLabel3 = new javax.swing.JLabel();
        txtpay = new Controls.JTextBox(15);
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rdoname = new javax.swing.JRadioButton();
        txtSearch1 = new Controls.JTextBox(10);
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        rdoNumber = new javax.swing.JRadioButton();
        bdnsearch1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        bdnadd = new javax.swing.JButton();
        bdndelete = new javax.swing.JButton();
        bdnclear = new javax.swing.JButton();
        bdnback = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        txtdate = new Controls.JTextBox(15);
        rdoaddress = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        txtidcol = new Controls.JTextBox(15);
        jLabel15 = new javax.swing.JLabel();
        rdopay = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rdoNum = new javax.swing.JRadioButton();
        rdoName = new javax.swing.JRadioButton();
        txtSearch = new Controls.JTextBox(10);
        rdodate = new javax.swing.JRadioButton();
        bdnsearch = new javax.swing.JButton();
        rdonotes = new javax.swing.JRadioButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtnotes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtnotes.setForeground(new java.awt.Color(0, 0, 0));
        txtnotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnotesActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("رقم المورد");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("اسم المورد");

        txtid1.setEditable(false);
        txtid1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtid1.setForeground(new java.awt.Color(0, 0, 0));
        txtid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid1ActionPerformed(evt);
            }
        });

        txtaddress.setEditable(false);
        txtaddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtaddress.setForeground(new java.awt.Color(0, 0, 0));
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });

        txtname.setEditable(false);
        txtname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(0, 0, 0));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("العنوان");

        txtpay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpay.setForeground(new java.awt.Color(0, 0, 0));
        txtpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpayActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("دفعنا");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ملاحظات");

        rdoname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoname.setForeground(new java.awt.Color(255, 255, 255));
        rdoname.setText("اسم المورد");
        rdoname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdonameActionPerformed(evt);
            }
        });

        txtSearch1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch1.setForeground(new java.awt.Color(0, 0, 0));
        txtSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearch1ActionPerformed(evt);
            }
        });

        tbl1.setAutoCreateRowSorter(true);
        tbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "رقم المورد", "اسم المورد", "العنوان"
            }
        ));
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tbl1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ابحث  عن المنتج باستخدام");

        rdoNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoNumber.setForeground(new java.awt.Color(255, 255, 255));
        rdoNumber.setSelected(true);
        rdoNumber.setText("رقم المورد");
        rdoNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNumberActionPerformed(evt);
            }
        });

        bdnsearch1.setBackground(new java.awt.Color(153, 255, 153));
        bdnsearch1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdnsearch1.setForeground(new java.awt.Color(0, 0, 0));
        bdnsearch1.setText(" بحث");
        bdnsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnsearch1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("التاريخ");

        bdnadd.setBackground(new java.awt.Color(0, 204, 51));
        bdnadd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnadd.setForeground(new java.awt.Color(255, 255, 255));
        bdnadd.setText("اضافة");
        bdnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnaddActionPerformed(evt);
            }
        });

        bdndelete.setBackground(new java.awt.Color(255, 0, 51));
        bdndelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdndelete.setForeground(new java.awt.Color(255, 255, 255));
        bdndelete.setText("حذف");
        bdndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdndeleteActionPerformed(evt);
            }
        });

        bdnclear.setBackground(new java.awt.Color(255, 255, 255));
        bdnclear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnclear.setForeground(new java.awt.Color(0, 0, 0));
        bdnclear.setText("البدء");
        bdnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnclearActionPerformed(evt);
            }
        });

        bdnback.setBackground(new java.awt.Color(255, 255, 255));
        bdnback.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnback.setForeground(new java.awt.Color(0, 0, 0));
        bdnback.setText("الرجوع");
        bdnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnbackActionPerformed(evt);
            }
        });

        tbl2.setAutoCreateRowSorter(true);
        tbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "رقم عملية الدفع", "رقم المورد", "اسم المورد", "دفعنا كام", "ملاحظات", "التاريخ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl2);

        txtdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtdate.setForeground(new java.awt.Color(0, 0, 0));
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });

        rdoaddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoaddress.setForeground(new java.awt.Color(255, 255, 255));
        rdoaddress.setText("العنوان");
        rdoaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoaddressActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 204));
        jLabel12.setText("نافذة الدفع للمورديين");

        txtidcol.setEditable(false);
        txtidcol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtidcol.setForeground(new java.awt.Color(0, 0, 0));
        txtidcol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidcolActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("رقم العملية");

        rdopay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdopay.setForeground(new java.awt.Color(255, 255, 255));
        rdopay.setText("دفعنا كام");
        rdopay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdopayActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ابحث باستخدام");

        rdoNum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoNum.setForeground(new java.awt.Color(255, 255, 255));
        rdoNum.setSelected(true);
        rdoNum.setText("رقم العملية");
        rdoNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNumActionPerformed(evt);
            }
        });

        rdoName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoName.setForeground(new java.awt.Color(255, 255, 255));
        rdoName.setText("اسم المورد");
        rdoName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNameActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        rdodate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdodate.setForeground(new java.awt.Color(255, 255, 255));
        rdodate.setText("التاريخ");
        rdodate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdodateActionPerformed(evt);
            }
        });

        bdnsearch.setBackground(new java.awt.Color(153, 255, 153));
        bdnsearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdnsearch.setForeground(new java.awt.Color(0, 0, 0));
        bdnsearch.setText(" بحث");
        bdnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnsearchActionPerformed(evt);
            }
        });

        rdonotes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdonotes.setForeground(new java.awt.Color(255, 255, 255));
        rdonotes.setText("ملاحظات");
        rdonotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdonotesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bdnsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoaddress)
                        .addGap(5, 5, 5)
                        .addComponent(rdoname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(bdnsearch)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdodate)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdopay))
                                    .addComponent(rdoName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoNum)
                                    .addComponent(rdonotes))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bdnadd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bdndelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bdnclear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bdnback, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtdate)
                                    .addComponent(txtpay, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnotes, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtidcol)
                                    .addComponent(txtaddress)
                                    .addComponent(txtname)
                                    .addComponent(txtid1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel15))))
                        .addGap(195, 195, 195))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(588, 588, 588))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoNumber)
                            .addComponent(rdoname)
                            .addComponent(jLabel6)
                            .addComponent(bdnsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoaddress))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(bdnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(bdndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(bdnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(bdnback, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rdoNum)
                                            .addComponent(rdoName))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdopay)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(rdodate)
                                                .addComponent(rdonotes))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bdnsearch))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtidcol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtnotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnotesActionPerformed

    private void txtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid1ActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpayActionPerformed

    private void rdonameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdonameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdonameActionPerformed

    private void txtSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearch1ActionPerformed
      
    }//GEN-LAST:event_txtSearch1ActionPerformed

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        try{

            int row = tbl1.getSelectedRow();

            String id =(String) tbl1.getValueAt(row , 0);
            String name = tbl1.getValueAt(row, 1).toString();
            String address =(String) tbl1.getValueAt(row, 2);

            txtid1.setText(id);
            txtname.setText(name);
            txtaddress.setText(address);
            
        txtidcol.setText(ic.getAutoNumber());
        txtdate.setText("");
                 
            txtnotes.setText("");
            txtpay.setText("");
          
          
            bdnadd.setEnabled(true);
         
            bdndelete.setEnabled(true);
        }
        catch(Exception ex){

            TheTools.msgBox(ex.getMessage());
        }
    }//GEN-LAST:event_tbl1MouseClicked

    private void tbl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl1MouseEntered

    private void rdoNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNumberActionPerformed
  
    
    PaymentClass ic = new PaymentClass();
        

    private void cleardata(){
        TheTools.clearText(this);
      
       
        bdnadd.setEnabled(true);
    
        bdndelete.setEnabled(false);
      
      txtidcol.setText(ic.getAutoNumber());
       txtSearch1.setText("0");
      
       
     
       
     
      
  
   
      ic.filesupplytable(tbl1);
     
       ic.getAllRows(tbl2);
      
    }
    
    

    private void setValue(){
   
    
    //combo
    
    ic.setPayementid(Integer.parseInt(txtidcol.getText()));
    ic.setSupplierid(Integer.parseInt(txtid1.getText()));
    ic.setName(txtname.getText());
    ic.setNotes(txtnotes.getText());
     ic.setDate(txtdate.getText());
     ic.setPay(Integer.parseInt(txtpay.getText()));
        
    
    
   
}
    private void bdnsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnsearch1ActionPerformed
        // TODO add your handling code here:

        String strSearch = "select `id` , `clientname` , `address` from customer where ";
        if(rdoNumber.isSelected()){
            strSearch += "id";
        }
        else if(rdoname.isSelected()){
            strSearch += "clientname";
        }
        else{
            strSearch += "address";
        }

        strSearch += " like '%"+  txtSearch1.getText()  +"%'";
        ic.getCustomRows(strSearch, tbl1);
    }//GEN-LAST:event_bdnsearch1ActionPerformed
 
     
 
    
    
    private void bdnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnaddActionPerformed
        // TODO add your handling code here:
        try{
           
           
            
            
            setValue();
          
             ic.add();
          ic.addinstore();
          ic.addinsupbalance();
            
      cleardata();

        }
        catch(Exception ex){
            /*
            String SPart = tableNameOrSelectStatement.substring(0, 7).toLowerCase();
            String strSelect;

            if("select ".equals(SPart)){
                strSelect = tableNameOrSelectStatement;
            }

            String message = ex.getMessage();

            if(message.startsWith("For input")){
                TheTools.msgBox("قم بادخال  جميع البيانات");
                TheTools.msgBox(ex.getMessage());
            } else {
                TheTools.msgBox("هناك خطأ ما");
                TheTools.msgBox(ex.getMessage());
            }
            */
            TheTools.msgBox(ex.getMessage());
        }
    }//GEN-LAST:event_bdnaddActionPerformed

    private void bdndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdndeleteActionPerformed
        // TODO add your handling code here:
        if(TheTools.confirmMsg("Did you really want to delete")){
            setValue();
            ic.delete();
            cleardata();

        }
    }//GEN-LAST:event_bdndeleteActionPerformed

    private void bdnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnclearActionPerformed
        // TODO add your handling code here:
        cleardata();
        tbl1.setSelectionMode(0);
    }//GEN-LAST:event_bdnclearActionPerformed

    private void bdnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnbackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        EnrollSupply emp = new EnrollSupply();

        emp.setLocationRelativeTo(null);
        emp.setDefaultCloseOperation(2);
        emp.getContentPane().setBackground(new Color(50, 100, 50));
        emp.setVisible(true);
    }//GEN-LAST:event_bdnbackActionPerformed

    private void tbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MouseClicked
        // TODO add your handling code here:

        try{
            int row = tbl2.getSelectedRow();

            String idcol =(String) tbl2.getValueAt(row , 0);
            String id = tbl2.getValueAt(row, 1).toString();
            String name =(String) tbl2.getValueAt(row, 2);
            

            String pay =(String) tbl2.getValueAt(row, 3);
            String notes =(String) tbl2.getValueAt(row, 4);
            String date =(String) tbl2.getValueAt(row, 5);
            
           
            txtidcol.setText(idcol);
            txtid1.setText(id);
            txtname.setText(name);
         

         txtdate.setText(date);
                 
            txtnotes.setText(notes);
            txtpay.setText(pay);
           txtaddress.setText("");
           txtidcol.setText(ic.getAutoNumber());
            bdnadd.setEnabled(false);
       
            bdndelete.setEnabled(true);
        }
        catch(Exception ex){

            TheTools.msgBox(ex.getMessage());
        }

    }//GEN-LAST:event_tbl2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
          // TODO add your handling code here:
        buttonGroup1.add(rdoNumber);
      buttonGroup1.add(rdoname);
        buttonGroup1.add(rdoaddress);
        
         buttonGroup2.add(rdoNum);
      buttonGroup2.add(rdoName);
        buttonGroup2.add(rdonotes);
         buttonGroup2.add(rdopay);
          buttonGroup2.add(rdodate);
      cleardata();
      
    }//GEN-LAST:event_formWindowOpened

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void rdoaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoaddressActionPerformed

    private void txtidcolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidcolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidcolActionPerformed

    private void rdopayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdopayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdopayActionPerformed

    private void rdoNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNumActionPerformed

    private void rdoNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNameActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed

    }//GEN-LAST:event_txtSearchActionPerformed

    private void rdodateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdodateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdodateActionPerformed

    private void bdnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnsearchActionPerformed
        // TODO add your handling code here:

        String strSearch = "select * from collection where ";
        if(rdoNumber.isSelected()){
            strSearch += "idcol ";
        }
        else if(rdoName.isSelected()){
            strSearch += "name";
        }
        else if(rdopay.isSelected()){
            strSearch += "pay";
        }
         else if(rdonotes.isSelected()){
            strSearch += "notes";
        }

        // else if(rdodetails.isSelected()){
            //      strSearch += "storename";
            //}
        else{
            strSearch += "date";
        }
        strSearch += " like '%"+  txtSearch.getText()  +"%'";
        ic.getCustomRows(strSearch, tbl2);
    }//GEN-LAST:event_bdnsearchActionPerformed

    private void rdonotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdonotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdonotesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdnadd;
    private javax.swing.JButton bdnback;
    private javax.swing.JButton bdnclear;
    private javax.swing.JButton bdndelete;
    private javax.swing.JButton bdnsearch;
    private javax.swing.JButton bdnsearch1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdoName;
    private javax.swing.JRadioButton rdoNum;
    private javax.swing.JRadioButton rdoNumber;
    private javax.swing.JRadioButton rdoaddress;
    private javax.swing.JRadioButton rdodate;
    private javax.swing.JRadioButton rdoname;
    private javax.swing.JRadioButton rdonotes;
    private javax.swing.JRadioButton rdopay;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtid1;
    private javax.swing.JTextField txtidcol;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnotes;
    private javax.swing.JTextField txtpay;
    // End of variables declaration//GEN-END:variables
}
