/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.EntityForms;

import Entity.Materials;
import Entity.Product;
import company.TheTools;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author framawy
 */
public class material extends javax.swing.JFrame {

    /**
     * Creates new form DepartmentForm
     */
    public material() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMyButton1 = new Controls.JMyButton();
        jMyButton8 = new Controls.JMyButton();
        btnGroub = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtype = new Controls.JTextBox(15);
        txtprice = new Controls.JTextBox(15);
        jLabel5 = new javax.swing.JLabel();
        rdoNumber = new javax.swing.JRadioButton();
        rdoName = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldept = new javax.swing.JTable();
        txtSearch = new Controls.JTextBox(10);
        txtname = new Controls.JTextBox(15);
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtweight = new Controls.JTextBox(15);
        rdoprice = new javax.swing.JRadioButton();
        rdotype = new javax.swing.JRadioButton();
        bdnadd = new javax.swing.JButton();
        bdnupdate = new javax.swing.JButton();
        bdndelete = new javax.swing.JButton();
        bdnback = new javax.swing.JButton();
        bdnfind = new javax.swing.JButton();
        bdnall = new javax.swing.JButton();
        bdnclear = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        bdnsearch = new javax.swing.JButton();

        jMyButton1.setText("jMyButton1");

        jMyButton8.setText("jMyButton8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("مواد خام المستخدمة فى التصنيع واحيانا للبيع ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("الرقم التعريفى");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("السعر");

        txtype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtype.setForeground(new java.awt.Color(0, 0, 0));
        txtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtypeActionPerformed(evt);
            }
        });

        txtprice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtprice.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ابحث باستخدام");

        rdoNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoNumber.setForeground(new java.awt.Color(255, 255, 255));
        rdoNumber.setSelected(true);
        rdoNumber.setText("الرقم التعريفى");
        rdoNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNumberActionPerformed(evt);
            }
        });

        rdoName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoName.setForeground(new java.awt.Color(255, 255, 255));
        rdoName.setText("اسم المنتج");
        rdoName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNameActionPerformed(evt);
            }
        });

        tbldept.setAutoCreateRowSorter(true);
        tbldept.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "الرقم التعريفى", "الصنف", "الوزن", "السعر", "نوع المنتج"
            }
        ));
        tbldept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldeptMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldept);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        txtname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("الوزن");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("اسم المنتج");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("نوع و تفاصيل  المنتج");

        txtweight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtweight.setForeground(new java.awt.Color(0, 0, 0));

        rdoprice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoprice.setForeground(new java.awt.Color(255, 255, 255));
        rdoprice.setText("السعر");
        rdoprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdopriceActionPerformed(evt);
            }
        });

        rdotype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdotype.setForeground(new java.awt.Color(255, 255, 255));
        rdotype.setText("نوع المنتج");
        rdotype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdotypeActionPerformed(evt);
            }
        });

        bdnadd.setBackground(new java.awt.Color(0, 204, 51));
        bdnadd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnadd.setForeground(new java.awt.Color(255, 255, 255));
        bdnadd.setText("اضافة");
        bdnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnaddActionPerformed(evt);
            }
        });

        bdnupdate.setBackground(new java.awt.Color(51, 51, 255));
        bdnupdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnupdate.setForeground(new java.awt.Color(255, 255, 255));
        bdnupdate.setText("تعديل");
        bdnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnupdateActionPerformed(evt);
            }
        });

        bdndelete.setBackground(new java.awt.Color(255, 0, 51));
        bdndelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdndelete.setForeground(new java.awt.Color(255, 255, 255));
        bdndelete.setText("حذف");
        bdndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdndeleteActionPerformed(evt);
            }
        });

        bdnback.setBackground(new java.awt.Color(255, 255, 255));
        bdnback.setForeground(new java.awt.Color(0, 0, 0));
        bdnback.setText("الرجوع");
        bdnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnbackActionPerformed(evt);
            }
        });

        bdnfind.setBackground(new java.awt.Color(204, 204, 204));
        bdnfind.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdnfind.setForeground(new java.awt.Color(0, 0, 0));
        bdnfind.setText("ايجاد المنتج باستخدام الرقم التعريفى");
        bdnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnfindActionPerformed(evt);
            }
        });

        bdnall.setBackground(new java.awt.Color(204, 204, 0));
        bdnall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdnall.setForeground(new java.awt.Color(0, 0, 0));
        bdnall.setText("اظهار كل المنتجات");
        bdnall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnallActionPerformed(evt);
            }
        });

        bdnclear.setBackground(new java.awt.Color(255, 255, 255));
        bdnclear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnclear.setForeground(new java.awt.Color(0, 0, 0));
        bdnclear.setText("البدء");
        bdnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnclearActionPerformed(evt);
            }
        });

        txtid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtid.setForeground(new java.awt.Color(0, 0, 0));

        bdnsearch.setBackground(new java.awt.Color(153, 255, 153));
        bdnsearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdnsearch.setForeground(new java.awt.Color(0, 0, 0));
        bdnsearch.setText(" بحث");
        bdnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(bdnsearch)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdoprice)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(rdotype)))
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bdnall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bdnfind, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bdnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bdndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bdnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bdnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bdnback, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtype, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(txtname)
                            .addComponent(txtprice)
                            .addComponent(txtweight)
                            .addComponent(txtid, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bdnsearch)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdotype)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rdoNumber)
                                .addComponent(rdoName)
                                .addComponent(rdoprice)))
                        .addGap(1, 1, 1)))
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdnfind, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bdnall, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(bdnback, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      btnGroub.add(rdoNumber);
      btnGroub.add(rdoName);
     
      btnGroub.add(rdoprice);
      btnGroub.add(rdotype);
      cleardata();
      mt.getAllRows(tbldept);
      txtSearch.setText("0");
       txtweight.setText("0");
       txtprice.setText("0");

      tbldept.getTableHeader().setReorderingAllowed(true);
    }//GEN-LAST:event_formWindowOpened

    Materials mt = new Materials();
    
    private void cleardata(){
        TheTools.clearText(this);
      
        txtid.setText(mt.getAutoNumber());
        bdnadd.setEnabled(true);
        bdnupdate.setEnabled(false);
        bdndelete.setEnabled(false);
        txtname.requestFocus();
         txtSearch.setText("0");
         txtprice.setText("0");
           txtweight.setText("0");
            
    }
    
    
    private void setValue(){
    mt.setId(Integer.parseInt(txtid.getText()));
    mt.setItem(txtname.getText());
    mt.setWeight(txtprice.getText());
    mt.setPrice(Float.parseFloat(txtweight.getText()));
    mt.setType(txtype.getText());
    
}
    
    private void tbldeptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldeptMouseClicked
        try{
        int row = tbldept.getSelectedRow();
        
        
        String id =(String) tbldept.getValueAt(row , 0);
        String item = tbldept.getValueAt(row, 1).toString();
        String weight =(String) tbldept.getValueAt(row, 2);
       
        String price =(String) tbldept.getValueAt(row , 3);
        String type =(String) tbldept.getValueAt(row, 4);


        txtid.setText(id);
        txtname.setText(item);
        txtweight.setText(weight);
        txtprice.setText(price);
        txtype.setText(type);
        
        bdnadd.setEnabled(false);
        bdnupdate.setEnabled(true);
        bdndelete.setEnabled(true);
        }
        catch(Exception ex){
            
            TheTools.msgBox(ex.getMessage());
        }
    }//GEN-LAST:event_tbldeptMouseClicked
 
    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
         txtSearch.setText("1");
    }//GEN-LAST:event_txtSearchActionPerformed

    private void rdoNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNameActionPerformed

    private void rdoNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNumberActionPerformed

    private void rdopriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdopriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdopriceActionPerformed

    private void rdotypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdotypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdotypeActionPerformed

    private void bdnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnbackActionPerformed
        // TODO add your handling code here:

       this.dispose();
       Entry emp = new Entry();
        
       
       emp.setLocationRelativeTo(null);
       emp.setDefaultCloseOperation(2);
       emp.getContentPane().setBackground(new Color(100, 20, 0));
       emp.setVisible(true);
    }//GEN-LAST:event_bdnbackActionPerformed

    private void bdnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnaddActionPerformed
        // TODO add your handling code here: 
      try{
         String txt = txtname.getText();
                if(txt.equals("")){
             TheTools.msgBox("قم بادخال المنتج");
           
          } 
              //if for if words up to 10  
             else{
       setValue();
        mt.add();
      cleardata();
      mt.getAllRows(tbldept);
                }
    }
       catch(Exception ex){
           /*
            String SPart = tableNameOrSelectStatement.substring(0, 7).toLowerCase();
         String strSelect;
          
         if("select ".equals(SPart)){
             strSelect = tableNameOrSelectStatement;
           }
             */
             
            
            String message = ex.getMessage();
             if(message.startsWith("For input")){
             TheTools.msgBox("قم بادخال  جميع البيانات");
             TheTools.msgBox(ex.getMessage());
          } else if(message.startsWith(" ")) {
               TheTools.msgBox("قم بادخال المنتج");
         
           
           } else if(message.startsWith("Data truncati")) {
               TheTools.msgBox("ضع رمز المنتج او الاسم الاول  فقط");
          TheTools.msgBox(ex.getMessage());
           }
           
          else {
                TheTools.msgBox("هناك خطأ ما");
                 TheTools.msgBox(ex.getMessage());
           }
        }
    }//GEN-LAST:event_bdnaddActionPerformed

    private void bdnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnupdateActionPerformed
        // TODO add your handling code here:
         
         
          setValue();
        mt.update();
        cleardata();
        mt.getAllRows(tbldept);
                
    }//GEN-LAST:event_bdnupdateActionPerformed

    private void bdndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdndeleteActionPerformed
        // TODO add your handling code here:
         if(TheTools.confirmMsg("Did you really want to delete")){
        setValue();
        mt.delete();
        cleardata();
        mt.getAllRows(tbldept);
       }
    }//GEN-LAST:event_bdndeleteActionPerformed

    private void bdnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnclearActionPerformed
        // TODO add your handling code here:
         cleardata();
        tbldept.setSelectionMode(0);
        
    }//GEN-LAST:event_bdnclearActionPerformed

    private void bdnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnfindActionPerformed
        // TODO add your handling code here
          String Strid =   JOptionPane.showInputDialog("أدخل اسم المنتج", null);
        mt.setId(Integer.parseInt(Strid));
     mt.getOneRow(tbldept);
    }//GEN-LAST:event_bdnfindActionPerformed

    private void bdnallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnallActionPerformed
        // TODO add your handling code here:
         mt.getAllRows(tbldept);
    }//GEN-LAST:event_bdnallActionPerformed

    private void txtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtypeActionPerformed

    private void bdnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnsearchActionPerformed
        // TODO add your handling code here:
        
        String strSearch = "select * from materials where ";
        if(rdoNumber.isSelected()){
            strSearch += "id ";
        }
        else if(rdoName.isSelected()){
            strSearch += "item";
        }
      
        else if(rdotype.isSelected()){
            strSearch += "type";
        }
        else{
            strSearch += "price";
        }
        strSearch += " like '%"+  txtSearch.getText()  +"%'";
        mt.getCustomRows(strSearch, tbldept);
    }//GEN-LAST:event_bdnsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new material().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdnadd;
    private javax.swing.JButton bdnall;
    private javax.swing.JButton bdnback;
    private javax.swing.JButton bdnclear;
    private javax.swing.JButton bdndelete;
    private javax.swing.JButton bdnfind;
    private javax.swing.JButton bdnsearch;
    private javax.swing.JButton bdnupdate;
    private javax.swing.ButtonGroup btnGroub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private Controls.JMyButton jMyButton1;
    private Controls.JMyButton jMyButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoName;
    private javax.swing.JRadioButton rdoNumber;
    private javax.swing.JRadioButton rdoprice;
    private javax.swing.JRadioButton rdotype;
    private javax.swing.JTable tbldept;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtweight;
    private javax.swing.JTextField txtype;
    // End of variables declaration//GEN-END:variables
}
