/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.EntityForms;

import Entity.Employee;
import Entity.Product;
import Entity.Supplier;
import company.TheTools;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author framawy
 */
public class supplier extends javax.swing.JFrame {

    /**
     * Creates new form DepartmentForm
     */
    public supplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMyButton1 = new Controls.JMyButton();
        jMyButton8 = new Controls.JMyButton();
        btnGroub = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txttype = new Controls.JTextBox(15);
        txtaddress = new Controls.JTextBox(15);
        jLabel5 = new javax.swing.JLabel();
        rdoNumber = new javax.swing.JRadioButton();
        rdodate = new javax.swing.JRadioButton();
        rdoName = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldsup = new javax.swing.JTable();
        txtSearch = new Controls.JTextBox(10);
        txtdetails = new Controls.JTextBox(15);
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtphone = new Controls.JTextBox(15);
        txtperson = new Controls.JTextBox(15);
        rdotype = new javax.swing.JRadioButton();
        rdoaddress = new javax.swing.JRadioButton();
        bdnadd = new javax.swing.JButton();
        bdnupdate = new javax.swing.JButton();
        bdndelete = new javax.swing.JButton();
        bdnback = new javax.swing.JButton();
        bdnfind = new javax.swing.JButton();
        bdnall = new javax.swing.JButton();
        bdnclear = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        bdnsearch = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txttname = new Controls.JTextBox(15);
        jLabel10 = new javax.swing.JLabel();
        rdodetails = new javax.swing.JRadioButton();
        txthismoney = new Controls.JTextBox(15);

        jMyButton1.setText("jMyButton1");

        jMyButton8.setText("jMyButton8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  مورديين  شركة الرحاب ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("الرقم التعريفى");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("العنوان");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("رقم الهاتف");

        txttype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttype.setForeground(new java.awt.Color(0, 0, 0));
        txttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttypeActionPerformed(evt);
            }
        });

        txtaddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtaddress.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ابحث باستخدام");

        rdoNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoNumber.setForeground(new java.awt.Color(255, 255, 255));
        rdoNumber.setSelected(true);
        rdoNumber.setText("الرقم التعريفى");
        rdoNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNumberActionPerformed(evt);
            }
        });

        rdodate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdodate.setForeground(new java.awt.Color(255, 255, 255));
        rdodate.setText("تاريخ تسليم الدفعة القادمة");
        rdodate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdodateActionPerformed(evt);
            }
        });

        rdoName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoName.setForeground(new java.awt.Color(255, 255, 255));
        rdoName.setText("اسم المورد");
        rdoName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNameActionPerformed(evt);
            }
        });

        tbldsup.setAutoCreateRowSorter(true);
        tbldsup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbldsup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "الرقم التعريفى", "اسم المورد", "تفاصيل عن الشركة", "العنوان", "رقم الهاتف", "نوعية المورد", "له كام", "اسم الشخص"
            }
        ));
        tbldsup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldsupMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldsup);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        txtdetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtdetails.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("اسم الشخص الذي يتم التعامل معاه");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("اسم الشركة و تفاصيل عنها");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ليه فلوس كام");

        txtphone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtphone.setForeground(new java.awt.Color(0, 0, 0));
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        txtperson.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtperson.setForeground(new java.awt.Color(0, 0, 0));
        txtperson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpersonActionPerformed(evt);
            }
        });

        rdotype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdotype.setForeground(new java.awt.Color(255, 255, 255));
        rdotype.setText("نوعية المورد");
        rdotype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdotypeActionPerformed(evt);
            }
        });

        rdoaddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoaddress.setForeground(new java.awt.Color(255, 255, 255));
        rdoaddress.setText("العنوان");
        rdoaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoaddressActionPerformed(evt);
            }
        });

        bdnadd.setBackground(new java.awt.Color(0, 204, 51));
        bdnadd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnadd.setForeground(new java.awt.Color(255, 255, 255));
        bdnadd.setText("اضافة");
        bdnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnaddActionPerformed(evt);
            }
        });

        bdnupdate.setBackground(new java.awt.Color(51, 51, 255));
        bdnupdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnupdate.setForeground(new java.awt.Color(255, 255, 255));
        bdnupdate.setText("تعديل");
        bdnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnupdateActionPerformed(evt);
            }
        });

        bdndelete.setBackground(new java.awt.Color(255, 0, 51));
        bdndelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdndelete.setForeground(new java.awt.Color(255, 255, 255));
        bdndelete.setText("حذف");
        bdndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdndeleteActionPerformed(evt);
            }
        });

        bdnback.setBackground(new java.awt.Color(255, 255, 255));
        bdnback.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdnback.setForeground(new java.awt.Color(0, 0, 0));
        bdnback.setText("الرجوع");
        bdnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnbackActionPerformed(evt);
            }
        });

        bdnfind.setBackground(new java.awt.Color(204, 204, 204));
        bdnfind.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdnfind.setForeground(new java.awt.Color(0, 0, 0));
        bdnfind.setText("ايجاد المورد باستخدام الرقم التعريفى");
        bdnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnfindActionPerformed(evt);
            }
        });

        bdnall.setBackground(new java.awt.Color(204, 204, 0));
        bdnall.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdnall.setForeground(new java.awt.Color(0, 0, 0));
        bdnall.setText("اظهار كل الموظفيين");
        bdnall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnallActionPerformed(evt);
            }
        });

        bdnclear.setBackground(new java.awt.Color(255, 255, 255));
        bdnclear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnclear.setForeground(new java.awt.Color(0, 0, 0));
        bdnclear.setText("البدء");
        bdnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnclearActionPerformed(evt);
            }
        });

        txtid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtid.setForeground(new java.awt.Color(0, 0, 0));
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        bdnsearch.setBackground(new java.awt.Color(153, 255, 153));
        bdnsearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdnsearch.setForeground(new java.awt.Color(0, 0, 0));
        bdnsearch.setText(" بحث");
        bdnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnsearchActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("اسم المورد");

        txttname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttname.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("نوعيد التوريد");

        rdodetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdodetails.setForeground(new java.awt.Color(255, 255, 255));
        rdodetails.setText("تفاصيل الشركة");
        rdodetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdodetailsActionPerformed(evt);
            }
        });

        txthismoney.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txthismoney.setForeground(new java.awt.Color(0, 0, 0));
        txthismoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthismoneyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(bdnsearch)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rdodate)
                                .addGap(30, 30, 30)
                                .addComponent(rdoName))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rdodetails)
                                .addGap(18, 18, 18)
                                .addComponent(rdotype)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(rdoaddress)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(bdnback, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(bdnfind, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(bdnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bdnall, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bdndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bdnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bdnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txttname)
                                                    .addComponent(txtid)
                                                    .addComponent(txtdetails)
                                                    .addComponent(txtaddress)
                                                    .addComponent(txtphone)
                                                    .addComponent(txttype)
                                                    .addComponent(txtperson)
                                                    .addComponent(txthismoney, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(10, 10, 10)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bdnsearch)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdoNumber)
                                    .addComponent(rdoName)
                                    .addComponent(rdodate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdotype)
                                    .addComponent(rdodetails)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdoaddress)
                                    .addComponent(jLabel5))
                                .addGap(1, 1, 1)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txthismoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtperson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bdnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdnall, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bdnfind, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdnback, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(420, 420, 420))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdodateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdodateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdodateActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      btnGroub.add(rdoNumber);
      btnGroub.add(rdoName);
      btnGroub.add(rdodate);
      btnGroub.add(rdoaddress);
      btnGroub.add(rdotype);
      btnGroub.add(rdodetails);
      
      cleardata();
      sp.getAllRows(tbldsup);
      txtSearch.setText("0");
       txtperson.setText("0");
      tbldsup.getTableHeader().setReorderingAllowed(true);
    }//GEN-LAST:event_formWindowOpened

     Supplier sp = new Supplier();
    
    private void cleardata(){
        TheTools.clearText(this);
      
        txtid.setText(sp.getAutoNumber());
        bdnadd.setEnabled(true);
        bdnupdate.setEnabled(false);
        bdndelete.setEnabled(false);
       txttname.requestFocus();
        sp.getAllRows(tbldsup);
         txtSearch.setText("0");
       
    }
    
    
    private void setValue(){
    sp.setId(Integer.parseInt(txtid.getText()));
    sp.setSuppliername(txttname.getText());
    sp.setDetails(txtdetails.getText());
    sp.setAddress(txtaddress.getText());
    sp.setPhone(txtphone.getText());
    sp.setType(txttype.getText());
    sp.setHismoney(Integer.parseInt(txthismoney.getText()));
    sp.setEmployee(txtperson.getText());
   
    
}
    
    private void tbldsupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldsupMouseClicked
        try{
        int row = tbldsup.getSelectedRow();
        
        
        String id =(String) tbldsup.getValueAt(row , 0);
        String name = tbldsup.getValueAt(row, 1).toString();
        String datails =(String) tbldsup.getValueAt(row, 2);
        String address =(String) tbldsup.getValueAt(row, 3);
        String phone =(String) tbldsup.getValueAt(row , 4);
        String type =(String) tbldsup.getValueAt(row, 5);
          String hismoney =(String) tbldsup.getValueAt(row, 6);
          String person =(String) tbldsup.getValueAt(row, 7);


        txtid.setText(id);
         txttname.setText(name);
        txtdetails.setText(datails);
        txtaddress.setText(address);
        txtphone.setText(phone);
        txttype.setText(type);
       txthismoney.setText(hismoney);
        txtperson.setText(person);
        
        bdnadd.setEnabled(false);
        bdnupdate.setEnabled(true);
        bdndelete.setEnabled(true);
        setValue();
         sp.updateforbalance();
         sp.getAllRows(tbldsup);
          String  newbalance =(String) tbldsup.getValueAt(row, 6);
          txthismoney.setText(newbalance);
        }
        catch(Exception ex){
            
            TheTools.msgBox(ex.getMessage());
        }
    }//GEN-LAST:event_tbldsupMouseClicked
 
    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
       
    }//GEN-LAST:event_txtSearchActionPerformed

    private void rdoNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNameActionPerformed

    private void rdoNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNumberActionPerformed

    private void rdotypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdotypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdotypeActionPerformed

    private void rdoaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoaddressActionPerformed

    private void bdnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnbackActionPerformed
        // TODO add your handling code here:
 this.dispose();
       Entry emp = new Entry();
        
       
       emp.setLocationRelativeTo(null);
       emp.setDefaultCloseOperation(2);
       emp.getContentPane().setBackground(new Color(100, 20, 0));
       emp.setVisible(true);
    }//GEN-LAST:event_bdnbackActionPerformed

    private void bdnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnaddActionPerformed
        // TODO add your handling code here: 
      try{
         setValue();
        sp.add();
        sp.addinsupplybalance();
      cleardata();
    
      
    }
       catch(Exception ex){
           /*
            String SPart = tableNameOrSelectStatement.substring(0, 7).toLowerCase();
         String strSelect;
          
         if("select ".equals(SPart)){
             strSelect = tableNameOrSelectStatement;
           }
             */
             String message = ex.getMessage();
             
             
         
          if(message.startsWith("For input")){
             TheTools.msgBox("قم بادخال  جميع البيانات");
           } else {
                TheTools.msgBox("هناك خطأ ما");
                 TheTools.msgBox(ex.getMessage());
           }
            
            
        }
    }//GEN-LAST:event_bdnaddActionPerformed

    private void bdnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnupdateActionPerformed
        // TODO add your handling code here:
         setValue();
        sp.update();
        cleardata();
        sp.getAllRows(tbldsup);
    }//GEN-LAST:event_bdnupdateActionPerformed

    private void bdndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdndeleteActionPerformed
        // TODO add your handling code here:
         if(TheTools.confirmMsg("Did you really want to delete")){
        setValue();
        sp.delete();
        cleardata();
        sp.getAllRows(tbldsup);
       }
    }//GEN-LAST:event_bdndeleteActionPerformed

    private void bdnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnclearActionPerformed
        // TODO add your handling code here:
         cleardata();
        tbldsup.setSelectionMode(0);
         
    }//GEN-LAST:event_bdnclearActionPerformed

    private void bdnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnfindActionPerformed
        // TODO add your handling code here
          String Strid =   JOptionPane.showInputDialog("أدخل اسم  المورد", null);
        sp.setId(Integer.parseInt(Strid));
     sp.getOneRow(tbldsup);
    }//GEN-LAST:event_bdnfindActionPerformed

    private void bdnallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnallActionPerformed
        // TODO add your handling code here:
         sp.getAllRows(tbldsup);
    }//GEN-LAST:event_bdnallActionPerformed

    private void txttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttypeActionPerformed

    private void bdnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnsearchActionPerformed
        // TODO add your handling code here:
        
        String strSearch = "select * from supplier where ";
        if(rdoNumber.isSelected()){
            strSearch += "id ";
        }
        else if(rdoName.isSelected()){
            strSearch += "suppliername";
        }
        else if(rdodate.isSelected()){
            strSearch += "paymentsdate";
        }
       
        else if(rdoaddress.isSelected()){
            strSearch += "address";
        }
         else if(rdotype.isSelected()){
            strSearch += "type";
        }
                else{
            strSearch += "details";
        }
        strSearch += " like '%"+  txtSearch.getText()  +"%'";
        setValue();
         sp.updateforbalance();
        
          int row = tbldsup.getSelectedRow();
         
        sp.getCustomRows(strSearch, tbldsup);
    }//GEN-LAST:event_bdnsearchActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtpersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpersonActionPerformed

    private void rdodetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdodetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdodetailsActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txthismoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthismoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthismoneyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdnadd;
    private javax.swing.JButton bdnall;
    private javax.swing.JButton bdnback;
    private javax.swing.JButton bdnclear;
    private javax.swing.JButton bdndelete;
    private javax.swing.JButton bdnfind;
    private javax.swing.JButton bdnsearch;
    private javax.swing.JButton bdnupdate;
    private javax.swing.ButtonGroup btnGroub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private Controls.JMyButton jMyButton1;
    private Controls.JMyButton jMyButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoName;
    private javax.swing.JRadioButton rdoNumber;
    private javax.swing.JRadioButton rdoaddress;
    private javax.swing.JRadioButton rdodate;
    private javax.swing.JRadioButton rdodetails;
    private javax.swing.JRadioButton rdotype;
    private javax.swing.JTable tbldsup;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtdetails;
    private javax.swing.JTextField txthismoney;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtperson;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txttname;
    private javax.swing.JTextField txttype;
    // End of variables declaration//GEN-END:variables
}
