/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package processForm;

import Forms.EntityForms.Entry;
import Process.Exportproduct;
import Process.Importclass;
import company.TheTools;
import java.awt.Color;

/**
 *
 * @author HP
 */
public class ExportForm extends javax.swing.JFrame {

    /**
     * Creates new form ImportForm2
     */
    public ExportForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        rdoName2 = new javax.swing.JRadioButton();
        txtSearch = new Controls.JTextBox(10);
        bdnsearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtId2 = new Controls.JTextBox(15);
        jLabel7 = new javax.swing.JLabel();
        txtweight = new Controls.JTextBox(15);
        txtname = new Controls.JTextBox(15);
        jLabel3 = new javax.swing.JLabel();
        clientnum = new Controls.JTextBox(15);
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtexp = new Controls.JTextBox(15);
        jLabel13 = new javax.swing.JLabel();
        clientname = new Controls.JTextBox(15);
        bdnadd = new javax.swing.JButton();
        bdnupdate = new javax.swing.JButton();
        bdndelete = new javax.swing.JButton();
        bdnclear = new javax.swing.JButton();
        bdnback = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtid1 = new Controls.JTextBox(15);
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        rdoName1 = new javax.swing.JRadioButton();
        txtSearch1 = new Controls.JTextBox(10);
        jLabel6 = new javax.swing.JLabel();
        rdoNumber = new javax.swing.JRadioButton();
        bdnsearch1 = new javax.swing.JButton();
        home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        rdoName2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoName2.setForeground(new java.awt.Color(255, 255, 255));
        rdoName2.setText("اسم العميل");
        rdoName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoName2ActionPerformed(evt);
            }
        });

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        bdnsearch.setBackground(new java.awt.Color(153, 255, 153));
        bdnsearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdnsearch.setForeground(new java.awt.Color(0, 0, 0));
        bdnsearch.setText(" بحث");
        bdnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnsearchActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ابحث  عن الزبون باستخدام");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("رقم المنتج");

        txtId2.setEditable(false);
        txtId2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtId2.setForeground(new java.awt.Color(0, 0, 0));
        txtId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("اسم المنتج");

        txtweight.setEditable(false);
        txtweight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtweight.setForeground(new java.awt.Color(0, 0, 0));
        txtweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtweightActionPerformed(evt);
            }
        });

        txtname.setEditable(false);
        txtname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(0, 0, 0));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("الوزن");

        clientnum.setEditable(false);
        clientnum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientnum.setForeground(new java.awt.Color(0, 0, 0));
        clientnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientnumActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("رقم العميل");

        tbl1.setAutoCreateRowSorter(true);
        tbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "رقم المنتج", "الصنف", "الوزن"
            }
        ));
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tbl1);

        tbl3.setAutoCreateRowSorter(true);
        tbl3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "الرقم التعريفى", "رقم المنتج", "الصنف", "الوزن", "الصادر", "رقم الزبون", "اسم الزبون"
            }
        ));
        tbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl3MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl3);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("اسم العميل");

        txtexp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtexp.setForeground(new java.awt.Color(0, 0, 0));
        txtexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexpActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("الصادر");

        clientname.setEditable(false);
        clientname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientname.setForeground(new java.awt.Color(0, 0, 0));
        clientname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientnameActionPerformed(evt);
            }
        });

        bdnadd.setBackground(new java.awt.Color(0, 204, 51));
        bdnadd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnadd.setForeground(new java.awt.Color(255, 255, 255));
        bdnadd.setText("اضافة");
        bdnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnaddActionPerformed(evt);
            }
        });

        bdnupdate.setBackground(new java.awt.Color(51, 51, 255));
        bdnupdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnupdate.setForeground(new java.awt.Color(255, 255, 255));
        bdnupdate.setText("تعديل");
        bdnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnupdateActionPerformed(evt);
            }
        });

        bdndelete.setBackground(new java.awt.Color(255, 0, 51));
        bdndelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdndelete.setForeground(new java.awt.Color(255, 255, 255));
        bdndelete.setText("حذف");
        bdndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdndeleteActionPerformed(evt);
            }
        });

        bdnclear.setBackground(new java.awt.Color(255, 255, 255));
        bdnclear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnclear.setForeground(new java.awt.Color(0, 0, 0));
        bdnclear.setText("البدء");
        bdnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnclearActionPerformed(evt);
            }
        });

        bdnback.setBackground(new java.awt.Color(255, 255, 255));
        bdnback.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnback.setForeground(new java.awt.Color(0, 0, 0));
        bdnback.setText("الرجوع للنافذة السابقة");
        bdnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnbackActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("الرقم التعريفى ");

        txtid1.setEditable(false);
        txtid1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtid1.setForeground(new java.awt.Color(0, 0, 0));
        txtid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid1ActionPerformed(evt);
            }
        });

        tbl2.setAutoCreateRowSorter(true);
        tbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "رقم العميل", "اسم العميل"
            }
        ));
        tbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl2MouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(tbl2);

        rdoName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoName1.setForeground(new java.awt.Color(255, 255, 255));
        rdoName1.setText("اسم المنتج");
        rdoName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoName1ActionPerformed(evt);
            }
        });

        txtSearch1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch1.setForeground(new java.awt.Color(0, 0, 0));
        txtSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearch1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ابحث  عن المنتج باستخدام");

        rdoNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoNumber.setForeground(new java.awt.Color(255, 255, 255));
        rdoNumber.setSelected(true);
        rdoNumber.setText("الرقم التعريفى");
        rdoNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNumberActionPerformed(evt);
            }
        });

        bdnsearch1.setBackground(new java.awt.Color(153, 255, 153));
        bdnsearch1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdnsearch1.setForeground(new java.awt.Color(0, 0, 0));
        bdnsearch1.setText(" بحث");
        bdnsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnsearch1ActionPerformed(evt);
            }
        });

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        home.setForeground(new java.awt.Color(0, 0, 0));
        home.setText("المنزل");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bdnback, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bdnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bdndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bdnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bdnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bdnsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdoName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoNumber)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6)))
                .addGap(0, 928, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtexp, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bdnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoName2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clientnum)
                                    .addComponent(clientname))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtweight)
                                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtid1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtId2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)))
                        .addGap(200, 200, 200)))
                .addGap(618, 618, 618))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoNumber)
                            .addComponent(rdoName1)
                            .addComponent(jLabel6)
                            .addComponent(bdnsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rdoName2)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bdnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(clientnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(clientname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtexp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bdnback, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoName2ActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        txtSearch.setText("1");
    }//GEN-LAST:event_txtSearchActionPerformed

    private void bdnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnsearchActionPerformed
        // TODO add your handling code here:

        String strSearch = "select `id` , `clientname`  from customer where `clientname`";
        

        strSearch += " like '%"+  txtSearch.getText()  +"%'";
        ic.getCustomRows(strSearch, tbl2);
    }//GEN-LAST:event_bdnsearchActionPerformed

    private void txtId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId2ActionPerformed

    private void txtweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtweightActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void clientnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientnumActionPerformed

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        try{
         
            int row = tbl1.getSelectedRow();

          String iditem =(String) tbl1.getValueAt(row , 0);
            String item = tbl1.getValueAt(row, 1).toString();
            String weight =(String) tbl1.getValueAt(row, 2);

              txtid1.setText(iditem);
            txtname.setText(item);
            txtweight.setText(weight);
              tbl1.clearSelection();
             tbl2.clearSelection();
             tbl3.clearSelection();
            bdnadd.setEnabled(true);
            bdnupdate.setEnabled(true);
            bdndelete.setEnabled(true);
        }
        catch(Exception ex){

            TheTools.msgBox(ex.getMessage());
        }
    }//GEN-LAST:event_tbl1MouseClicked

    private void tbl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl3MouseClicked
        // TODO add your handling code here:
        
          try{
            int row = tbl3.getSelectedRow();

            String id =(String) tbl3.getValueAt(row , 0);
            String iditem = tbl3.getValueAt(row, 1).toString();
            String item =(String) tbl3.getValueAt(row, 2);
            String weight =(String) tbl3.getValueAt(row, 3);

            String exp =(String) tbl3.getValueAt(row, 4);
             String cliennum =(String) tbl3.getValueAt(row, 5);
            String clienname =(String) tbl3.getValueAt(row , 6);
          
            
             txtId2.setText(id);
             txtid1.setText(iditem);
            txtname.setText(item);
            txtweight.setText(weight);
           
            
             tbl1.clearSelection();
             tbl2.clearSelection();
             tbl3.clearSelection();
            
            txtexp.setText(exp);
            clientname.setText(cliennum);
            clientnum.setText(clienname);
          

            bdnadd.setEnabled(false);
            bdnupdate.setEnabled(true);
            bdndelete.setEnabled(true);
        }
        catch(Exception ex){

            TheTools.msgBox(ex.getMessage());
        }
        
      
        
        
    }//GEN-LAST:event_tbl3MouseClicked

    
    Exportproduct ic = new Exportproduct();
    
    private void cleardata(){
        TheTools.clearText(this);
      
       
        bdnadd.setEnabled(true);
        bdnupdate.setEnabled(false);
        bdndelete.setEnabled(false);
       txtexp.requestFocus();
      txtId2.setText(ic.getAutoNumber());
       txtSearch.setText("0");
       
     
        txtexp.setText("0");
     
       
  
   
      ic.fileproducttable(tbl1);
      ic.fileclienttable(tbl2);
       ic.getAllRows(tbl3);
      
    }
    
    

    private void setValue(){
   
    
    //combo
    
    ic.setIditem(Integer.parseInt(txtid1.getText()));
    ic.setItem(txtname.getText());
    ic.setWeight(txtweight.getText());
    
     ic.setId(Integer.parseInt(txtId2.getText()));
      ic.setClientname(clientname.getText());
    ic.setClientid(Integer.parseInt(clientnum.getText()));
    
    
     ic.setExp(Integer.parseInt(txtexp.getText()));
   
   
   
    
}
    
    
    
    
    

    private void txtexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtexpActionPerformed

    private void clientnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientnameActionPerformed

    private void bdnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnaddActionPerformed
        // TODO add your handling code here:
        try{
            setValue();
            ic.add();
            ic.addinthestore();
            ic.addinproductbalance();
            cleardata();

        }
        catch(Exception ex){
            /*
            String SPart = tableNameOrSelectStatement.substring(0, 7).toLowerCase();
            String strSelect;

            if("select ".equals(SPart)){
                strSelect = tableNameOrSelectStatement;
            }

            String message = ex.getMessage();

            if(message.startsWith("For input")){
                TheTools.msgBox("قم بادخال  جميع البيانات");
                TheTools.msgBox(ex.getMessage());
            } else {
                TheTools.msgBox("هناك خطأ ما");
                TheTools.msgBox(ex.getMessage());
            }
            */
            TheTools.msgBox(ex.getMessage());
        }
    }//GEN-LAST:event_bdnaddActionPerformed

    private void bdnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnupdateActionPerformed
        // TODO add your handling code here:
        setValue();
        ic.update();
        cleardata();

    }//GEN-LAST:event_bdnupdateActionPerformed

    private void bdndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdndeleteActionPerformed
        // TODO add your handling code here:
        if(TheTools.confirmMsg("Did you really want to delete")){
            setValue();
            ic.delete();
            cleardata();

        }
    }//GEN-LAST:event_bdndeleteActionPerformed

    private void bdnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnclearActionPerformed
        // TODO add your handling code here:
        cleardata();
        tbl1.setSelectionMode(0);
    }//GEN-LAST:event_bdnclearActionPerformed

    private void bdnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnbackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        EnrollStore emp = new EnrollStore();

        emp.setLocationRelativeTo(null);
        emp.setDefaultCloseOperation(2);
        emp.getContentPane().setBackground(new Color(190, 40, 0));
        emp.setVisible(true);
    }//GEN-LAST:event_bdnbackActionPerformed

    private void txtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
          // TODO add your handling code here:
        buttonGroup1.add(rdoNumber);
      buttonGroup1.add(rdoName1);
     buttonGroup2.add(rdoName2);
      cleardata();
    
      
      
        
    }//GEN-LAST:event_formWindowOpened

    private void tbl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl1MouseEntered

    private void tbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MouseClicked
        // TODO add your handling code here:
          try{
         
            int row = tbl2.getSelectedRow();

         
            String custnum = tbl2.getValueAt(row, 0).toString();
            String custname =(String) tbl2.getValueAt(row, 1);

             
             tbl1.clearSelection();
             tbl2.clearSelection();
             tbl3.clearSelection();
            
            
            clientnum.setText(custnum);
            clientname.setText(custname);
            
            bdnadd.setEnabled(true);
            bdnupdate.setEnabled(true);
            bdndelete.setEnabled(true);
        }
        catch(Exception ex){

            TheTools.msgBox(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_tbl2MouseClicked

    private void tbl2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl2MouseEntered

    private void rdoName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoName1ActionPerformed

    private void txtSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearch1ActionPerformed
        txtSearch.setText("1");
    }//GEN-LAST:event_txtSearch1ActionPerformed

    private void rdoNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNumberActionPerformed

    private void bdnsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnsearch1ActionPerformed
        // TODO add your handling code here:

        String strSearch = "select `id` , `item` , `weight` from product where ";
        if(rdoNumber.isSelected()){
            strSearch += "id ";
        }
        else if(rdoName1.isSelected()){
            strSearch += "item";
        }

        strSearch += " like '%"+  txtSearch.getText()  +"%'";
        ic.getCustomRows(strSearch, tbl1);
    }//GEN-LAST:event_bdnsearch1ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Entry en = new Entry();

        en.setLocationRelativeTo(null);
        en.setDefaultCloseOperation(2);
        en.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExportForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdnadd;
    private javax.swing.JButton bdnback;
    private javax.swing.JButton bdnclear;
    private javax.swing.JButton bdndelete;
    private javax.swing.JButton bdnsearch;
    private javax.swing.JButton bdnsearch1;
    private javax.swing.JButton bdnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField clientname;
    private javax.swing.JTextField clientnum;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdoName1;
    private javax.swing.JRadioButton rdoName2;
    private javax.swing.JRadioButton rdoNumber;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    private javax.swing.JTable tbl3;
    private javax.swing.JTextField txtId2;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtexp;
    private javax.swing.JTextField txtid1;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtweight;
    // End of variables declaration//GEN-END:variables
}
