/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package processForm;

import Process.Importclass;
import Process.store;
import company.TheTools;
import java.awt.Color;

/**
 *
 * @author HP
 */
public class importform extends javax.swing.JFrame {

   
    public importform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        mixname = new Controls.JTextBox(15);
        jLabel9 = new javax.swing.JLabel();
        txtId2 = new Controls.JTextBox(15);
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtid1 = new Controls.JTextBox(15);
        txtweight = new Controls.JTextBox(15);
        txtname = new Controls.JTextBox(15);
        jLabel3 = new javax.swing.JLabel();
        mixnum = new Controls.JTextBox(15);
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rdoName1 = new javax.swing.JRadioButton();
        txtSearch1 = new Controls.JTextBox(10);
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        rdoNumber = new javax.swing.JRadioButton();
        bdnsearch1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        bdnadd = new javax.swing.JButton();
        bdnupdate = new javax.swing.JButton();
        bdndelete = new javax.swing.JButton();
        bdnclear = new javax.swing.JButton();
        bdnback = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();
        txtimp1 = new Controls.JTextBox(15);
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bdnback1 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mixname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mixname.setForeground(new java.awt.Color(0, 0, 0));
        mixname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixnameActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("رقم المنتج");

        txtId2.setEditable(false);
        txtId2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtId2.setForeground(new java.awt.Color(0, 0, 0));
        txtId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("اسم المنتج");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("الرقم التعريفى ");

        txtid1.setEditable(false);
        txtid1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtid1.setForeground(new java.awt.Color(0, 0, 0));
        txtid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid1ActionPerformed(evt);
            }
        });

        txtweight.setEditable(false);
        txtweight.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtweight.setForeground(new java.awt.Color(0, 0, 0));
        txtweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtweightActionPerformed(evt);
            }
        });

        txtname.setEditable(false);
        txtname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(0, 0, 0));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("الوزن");

        mixnum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mixnum.setForeground(new java.awt.Color(0, 0, 0));
        mixnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mixnumActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("تاريخ  العملية");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("من أين");

        rdoName1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoName1.setForeground(new java.awt.Color(255, 255, 255));
        rdoName1.setText("اسم المنتج");
        rdoName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoName1ActionPerformed(evt);
            }
        });

        txtSearch1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch1.setForeground(new java.awt.Color(0, 0, 0));
        txtSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearch1ActionPerformed(evt);
            }
        });

        tbl1.setAutoCreateRowSorter(true);
        tbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "رقم المنتج", "الصنف", "الوزن"
            }
        ));
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tbl1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ابحث  عن المنتج باستخدام");

        rdoNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoNumber.setForeground(new java.awt.Color(255, 255, 255));
        rdoNumber.setSelected(true);
        rdoNumber.setText("الرقم التعريفى");
        rdoNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNumberActionPerformed(evt);
            }
        });

        bdnsearch1.setBackground(new java.awt.Color(153, 255, 153));
        bdnsearch1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bdnsearch1.setForeground(new java.awt.Color(0, 0, 0));
        bdnsearch1.setText(" بحث");
        bdnsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnsearch1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("الوارد");

        bdnadd.setBackground(new java.awt.Color(0, 204, 51));
        bdnadd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnadd.setForeground(new java.awt.Color(255, 255, 255));
        bdnadd.setText("اضافة");
        bdnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnaddActionPerformed(evt);
            }
        });

        bdnupdate.setBackground(new java.awt.Color(51, 51, 255));
        bdnupdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnupdate.setForeground(new java.awt.Color(255, 255, 255));
        bdnupdate.setText("تعديل");
        bdnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnupdateActionPerformed(evt);
            }
        });

        bdndelete.setBackground(new java.awt.Color(255, 0, 51));
        bdndelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdndelete.setForeground(new java.awt.Color(255, 255, 255));
        bdndelete.setText("حذف");
        bdndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdndeleteActionPerformed(evt);
            }
        });

        bdnclear.setBackground(new java.awt.Color(255, 255, 255));
        bdnclear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnclear.setForeground(new java.awt.Color(0, 0, 0));
        bdnclear.setText("البدء");
        bdnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnclearActionPerformed(evt);
            }
        });

        bdnback.setBackground(new java.awt.Color(255, 255, 255));
        bdnback.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnback.setForeground(new java.awt.Color(0, 0, 0));
        bdnback.setText("الرجوع للنافذة السابقة");
        bdnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdnbackActionPerformed(evt);
            }
        });

        tbl2.setAutoCreateRowSorter(true);
        tbl2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "الرقم التعريفى", "رقم المنتج", "الصنف", "الوزن", "الوارد", "تاريخ الخلطة", "اسم الخلطة"
            }
        ));
        tbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl2);

        txtimp1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtimp1.setForeground(new java.awt.Color(0, 0, 0));
        txtimp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimp1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("جدول المنتجات");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("  جدول المنتجات الواردة");

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("نافذة المنتجات الواردة");

        bdnback1.setBackground(new java.awt.Color(255, 255, 255));
        bdnback1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bdnback1.setForeground(new java.awt.Color(0, 0, 0));
        bdnback1.setText("المنزل");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mixnum)
                                            .addComponent(mixname))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtweight)
                                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtid1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtId2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtimp1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(68, 68, 68)
                                    .addComponent(jLabel13))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bdndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(bdnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bdnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bdnback, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bdnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(bdnback1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(348, 348, 348))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(bdnsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdoName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoNumber)
                            .addComponent(rdoName1)
                            .addComponent(bdnsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mixnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(mixname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtimp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bdnupdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bdndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bdnadd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bdnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bdnback, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bdnback1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mixnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mixnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mixnameActionPerformed

    private void txtId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId2ActionPerformed

    private void txtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid1ActionPerformed

    private void txtweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtweightActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void mixnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mixnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mixnumActionPerformed

    private void rdoName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoName1ActionPerformed

    private void txtSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearch1ActionPerformed
      
    }//GEN-LAST:event_txtSearch1ActionPerformed

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        try{

            int row = tbl1.getSelectedRow();

            String iditem =(String) tbl1.getValueAt(row , 0);
            String item = tbl1.getValueAt(row, 1).toString();
            String weight =(String) tbl1.getValueAt(row, 2);

            txtid1.setText(iditem);
            txtname.setText(item);
            txtweight.setText(weight);

             tbl1.clearSelection();
             tbl2.clearSelection();
            
            
            bdnadd.setEnabled(true);
            bdnupdate.setEnabled(true);
            bdndelete.setEnabled(true);
        }
        catch(Exception ex){

            TheTools.msgBox(ex.getMessage());
        }
    }//GEN-LAST:event_tbl1MouseClicked

    private void tbl1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl1MouseEntered

    private void rdoNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNumberActionPerformed
  
    
    Importclass ic = new Importclass();
        

    private void cleardata(){
        TheTools.clearText(this);
      
       
        bdnadd.setEnabled(true);
        bdnupdate.setEnabled(false);
        bdndelete.setEnabled(false);
      
      txtId2.setText(ic.getAutoNumber());
       txtSearch1.setText("0");
        txtimp1.setText("0");
       
     
       
     
      
  
   
      ic.fileproducttable(tbl1);
     
       ic.getAllRows(tbl2);
      
    }
    
    

    private void setValue(){
   
    
    //combo
    
    ic.setIditem(Integer.parseInt(txtid1.getText()));
    ic.setItem(txtname.getText());
    ic.setWeight(txtweight.getText());
    
     ic.setId(Integer.parseInt(txtId2.getText()));
      ic.setMixturename(mixname.getText());
    ic.setMixtureid(mixnum.getText());
    
    
     ic.setImp(Integer.parseInt(txtimp1.getText()));
   
   
}
    private void bdnsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnsearch1ActionPerformed
         // TODO add your handling code here:

        String strSearch = "select `id` , `item` , `weight` from product where ";
      String strSearch2 = "select * from `productsimport` where ";
        if(rdoNumber.isSelected()){
            strSearch += "id ";
             strSearch2 += "id";
        }
        else if(rdoName1.isSelected()){
            strSearch += "item";
             strSearch2 += "item";
        }

        strSearch += " like '%"+  txtSearch1.getText()  +"%'";
        strSearch2 += " like '%"+  txtSearch1.getText()  +"%'";
        ic.getCustomRows(strSearch, tbl1);
         ic.getCustomRows(strSearch2, tbl2);
        
        /*
         String strSearch = "select * from storeproduct where ";
        String strSearch2 = "select * from `productbalance` where ";
        if(rdoNumber.isSelected()){
            strSearch += "iditem";
            strSearch2 += "id";
        }
        else if(rdoName.isSelected()){
            strSearch += "item";
            strSearch2 += "item";
        }else {
            strSearch += "balance";
            strSearch2 += "balance";
        }

        strSearch += " like '%"+  txtSearch.getText()  +"%'";
        strSearch2 += " like '%"+  txtSearch.getText()  +"%'";
        st.getCustomRows(strSearch, tbl);
        st.getCustomRows(strSearch2, tbl2);
    }                                        
        */
    }//GEN-LAST:event_bdnsearch1ActionPerformed
 
     
    store st = new store();
    
    
    private void bdnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnaddActionPerformed
        // TODO add your handling code here:
        try{
           
           
            
            
            setValue();
          
             ic.add();
           ic.addinstore();
           ic.addinproductbalance();
            
      cleardata();

        }
        catch(Exception ex){
            /*
            String SPart = tableNameOrSelectStatement.substring(0, 7).toLowerCase();
            String strSelect;

            if("select ".equals(SPart)){
                strSelect = tableNameOrSelectStatement;
            }

            String message = ex.getMessage();

            if(message.startsWith("For input")){
                TheTools.msgBox("قم بادخال  جميع البيانات");
                TheTools.msgBox(ex.getMessage());
            } else {
                TheTools.msgBox("هناك خطأ ما");
                TheTools.msgBox(ex.getMessage());
            }
            */
            TheTools.msgBox(ex.getMessage());
        }
    }//GEN-LAST:event_bdnaddActionPerformed

    private void bdnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnupdateActionPerformed
        // TODO add your handling code here:
        setValue();
        ic.update();
        cleardata();
    }//GEN-LAST:event_bdnupdateActionPerformed

    private void bdndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdndeleteActionPerformed
        // TODO add your handling code here:
        if(TheTools.confirmMsg("Did you really want to delete")){
            setValue();
            ic.delete();
            cleardata();

        }
    }//GEN-LAST:event_bdndeleteActionPerformed

    private void bdnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnclearActionPerformed
        // TODO add your handling code here:
        cleardata();
        tbl1.setSelectionMode(0);
    }//GEN-LAST:event_bdnclearActionPerformed

    private void bdnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdnbackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        EnrollStore emp = new EnrollStore();

        emp.setLocationRelativeTo(null);
        emp.setDefaultCloseOperation(2);
        emp.getContentPane().setBackground(new Color(100, 0, 50));
        emp.setVisible(true);
    }//GEN-LAST:event_bdnbackActionPerformed

    private void tbl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MouseClicked
        // TODO add your handling code here:

        try{
            int row = tbl2.getSelectedRow();

            String id =(String) tbl2.getValueAt(row , 0);
            String iditem = tbl2.getValueAt(row, 1).toString();
            String item =(String) tbl2.getValueAt(row, 2);
            String weight =(String) tbl2.getValueAt(row, 3);

            String imp =(String) tbl2.getValueAt(row, 4);
            String cliennum =(String) tbl2.getValueAt(row, 5);
            String clienname =(String) tbl2.getValueAt(row , 6);
           
            txtId2.setText(id);
            txtid1.setText(iditem);
            txtname.setText(item);
            txtweight.setText(weight);

         txtimp1.setText(imp);
                 
            mixname.setText(cliennum);
            mixnum.setText(clienname);
          
            bdnadd.setEnabled(false);
            bdnupdate.setEnabled(true);
            bdndelete.setEnabled(true);
        }
        catch(Exception ex){

            TheTools.msgBox(ex.getMessage());
        }

    }//GEN-LAST:event_tbl2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
          // TODO add your handling code here:
        buttonGroup1.add(rdoNumber);
      buttonGroup1.add(rdoName1);
     
      cleardata();
      
    }//GEN-LAST:event_formWindowOpened

    private void txtimp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtimp1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(importform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(importform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(importform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(importform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new importform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdnadd;
    private javax.swing.JButton bdnback;
    private javax.swing.JButton bdnback1;
    private javax.swing.JButton bdnclear;
    private javax.swing.JButton bdndelete;
    private javax.swing.JButton bdnsearch1;
    private javax.swing.JButton bdnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mixname;
    private javax.swing.JTextField mixnum;
    private javax.swing.JRadioButton rdoName1;
    private javax.swing.JRadioButton rdoNumber;
    private javax.swing.JTable tbl1;
    private javax.swing.JTable tbl2;
    private javax.swing.JTextField txtId2;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtid1;
    private javax.swing.JTextField txtimp1;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtweight;
    // End of variables declaration//GEN-END:variables
}
